#pragma once

#include <cstdint>

namespace Age::Core
{
enum struct ComponentType : std::uint16_t
{
    TRANSFORM,
    LOCAL_TO_VIEW_MATRIX,
    LOCAL_TO_VIEW_NORMAL_MATRIX,

    MATERIAL,

    MESH,

    UNIFORM_BUFFER_RANGE_BIND,
    UNIFORM_BUFFER_BLOCK,

    WORLD_TO_VIEW_MATRIX,
    VIEW_TO_CLIP_MATRIX,
    PERSPECTIVE_CAMERA,
    ORTHOGRAPHIC_CAMERA,
    WINDOW_SPACE_CAMERA,
    PROJECTION_BUFFER_BLOCK,

    GLOBAL_LIGHT_SETTINGS,
    DIRECTIONAL_LIGHT,
    POINT_LIGHT,
    LIGHTS_BUFFER_BLOCK,

    RENDER_STATE,
    RENDERER,

    SPHERICAL_CAMERA,

    MOUSE_INPUT,

    PATH_FOLLOWER,

    LAST_VALUE
};
} // namespace Age::Core
